/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipClubRouteImport } from './routes/vip-club'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatPageRouteImport } from './routes/_authenticated/chat.page'
import { Route as AuthenticatedChatFriendIdRouteImport } from './routes/_authenticated/chat.$friendId'

const VipClubRoute = VipClubRouteImport.update({
  id: '/vip-club',
  path: '/vip-club',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatPageRoute = AuthenticatedChatPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatFriendIdRoute =
  AuthenticatedChatFriendIdRouteImport.update({
    id: '/$friendId',
    path: '/$friendId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip-club': typeof VipClubRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/chat/page': typeof AuthenticatedChatPageRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip-club': typeof VipClubRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/chat/page': typeof AuthenticatedChatPageRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip-club': typeof VipClubRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/_authenticated/chat/page': typeof AuthenticatedChatPageRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip-club'
    | '/admin'
    | '/chat'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/chat/$friendId'
    | '/chat/page'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip-club'
    | '/admin'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/chat/$friendId'
    | '/chat/page'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip-club'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/friends'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/chat/$friendId'
    | '/_authenticated/chat/page'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogRoute: typeof BlogRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  PromotionsRoute: typeof PromotionsRoute
  ReferralRoute: typeof ReferralRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  VipClubRoute: typeof VipClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-club': {
      id: '/vip-club'
      path: '/vip-club'
      fullPath: '/vip-club'
      preLoaderRoute: typeof VipClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/page': {
      id: '/_authenticated/chat/page'
      path: '/page'
      fullPath: '/chat/page'
      preLoaderRoute: typeof AuthenticatedChatPageRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$friendId': {
      id: '/_authenticated/chat/$friendId'
      path: '/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof AuthenticatedChatFriendIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatFriendIdRoute: typeof AuthenticatedChatFriendIdRoute
  AuthenticatedChatPageRoute: typeof AuthenticatedChatPageRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatFriendIdRoute: AuthenticatedChatFriendIdRoute,
  AuthenticatedChatPageRoute: AuthenticatedChatPageRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogRoute: BlogRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  PromotionsRoute: PromotionsRoute,
  ReferralRoute: ReferralRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  VipClubRoute: VipClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
