/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipClubRouteImport } from './routes/vip-club'
import { Route as VipRouteImport } from './routes/vip'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVerifyOtpRouteImport } from './routes/app/verify-otp'
import { Route as AppResetPasswordRouteImport } from './routes/app/reset-password'
import { Route as AppForgotPasswordRouteImport } from './routes/app/forgot-password'
import { Route as AppAuthCallbackRouteImport } from './routes/app/auth-callback'
import { Route as AppAuthRouteImport } from './routes/app/auth'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AppAuthenticatedWalletRouteImport } from './routes/app/_authenticated/wallet'
import { Route as AppAuthenticatedVipRewardsRouteImport } from './routes/app/_authenticated/vip-rewards'
import { Route as AppAuthenticatedSecurityRouteImport } from './routes/app/_authenticated/security'
import { Route as AppAuthenticatedReferEarnRouteImport } from './routes/app/_authenticated/refer-earn'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/app/_authenticated/profile'
import { Route as AppAuthenticatedOnboardingRouteImport } from './routes/app/_authenticated/onboarding'
import { Route as AppAuthenticatedLeaderboardRouteImport } from './routes/app/_authenticated/leaderboard'
import { Route as AppAuthenticatedFriendsRouteImport } from './routes/app/_authenticated/friends'
import { Route as AppAuthenticatedChatRouteImport } from './routes/app/_authenticated/chat'
import { Route as AppAuthenticatedAdminRouteImport } from './routes/app/_authenticated/admin'
import { Route as AuthenticatedChatPageRouteImport } from './routes/_authenticated/chat.page'
import { Route as AuthenticatedChatFriendIdRouteImport } from './routes/_authenticated/chat.$friendId'
import { Route as AppAuthenticatedChatIndexRouteImport } from './routes/app/_authenticated/chat.index'
import { Route as AppAuthenticatedUUsernameRouteImport } from './routes/app/_authenticated/u.$username'
import { Route as AppAuthenticatedChatPageRouteImport } from './routes/app/_authenticated/chat.page'
import { Route as AppAuthenticatedChatFriendIdRouteImport } from './routes/app/_authenticated/chat.$friendId'
import { Route as AppAuthenticatedChatInviteTokenRouteImport } from './routes/app/_authenticated/chat.invite.$token'

const VipClubRoute = VipClubRouteImport.update({
  id: '/vip-club',
  path: '/vip-club',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyOtpRoute = AppVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthCallbackRoute = AppAuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AppAuthenticatedWalletRoute = AppAuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedVipRewardsRoute =
  AppAuthenticatedVipRewardsRouteImport.update({
    id: '/vip-rewards',
    path: '/vip-rewards',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedSecurityRoute =
  AppAuthenticatedSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedReferEarnRoute =
  AppAuthenticatedReferEarnRouteImport.update({
    id: '/refer-earn',
    path: '/refer-earn',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedOnboardingRoute =
  AppAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedLeaderboardRoute =
  AppAuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedFriendsRoute = AppAuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedChatRoute = AppAuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedAdminRoute = AppAuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AuthenticatedChatPageRoute = AuthenticatedChatPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatFriendIdRoute =
  AuthenticatedChatFriendIdRouteImport.update({
    id: '/$friendId',
    path: '/$friendId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AppAuthenticatedChatIndexRoute =
  AppAuthenticatedChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedChatRoute,
  } as any)
const AppAuthenticatedUUsernameRoute =
  AppAuthenticatedUUsernameRouteImport.update({
    id: '/u/$username',
    path: '/u/$username',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedChatPageRoute =
  AppAuthenticatedChatPageRouteImport.update({
    id: '/page',
    path: '/page',
    getParentRoute: () => AppAuthenticatedChatRoute,
  } as any)
const AppAuthenticatedChatFriendIdRoute =
  AppAuthenticatedChatFriendIdRouteImport.update({
    id: '/$friendId',
    path: '/$friendId',
    getParentRoute: () => AppAuthenticatedChatRoute,
  } as any)
const AppAuthenticatedChatInviteTokenRoute =
  AppAuthenticatedChatInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AppAuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip': typeof VipRoute
  '/vip-club': typeof VipClubRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app/auth': typeof AppAuthRoute
  '/app/auth-callback': typeof AppAuthCallbackRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/verify-otp': typeof AppVerifyOtpRoute
  '/app/': typeof AppIndexRoute
  '/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/chat/page': typeof AuthenticatedChatPageRoute
  '/app/admin': typeof AppAuthenticatedAdminRoute
  '/app/chat': typeof AppAuthenticatedChatRouteWithChildren
  '/app/friends': typeof AppAuthenticatedFriendsRoute
  '/app/leaderboard': typeof AppAuthenticatedLeaderboardRoute
  '/app/onboarding': typeof AppAuthenticatedOnboardingRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/refer-earn': typeof AppAuthenticatedReferEarnRoute
  '/app/security': typeof AppAuthenticatedSecurityRoute
  '/app/vip-rewards': typeof AppAuthenticatedVipRewardsRoute
  '/app/wallet': typeof AppAuthenticatedWalletRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/app/chat/$friendId': typeof AppAuthenticatedChatFriendIdRoute
  '/app/chat/page': typeof AppAuthenticatedChatPageRoute
  '/app/u/$username': typeof AppAuthenticatedUUsernameRoute
  '/app/chat/': typeof AppAuthenticatedChatIndexRoute
  '/app/chat/invite/$token': typeof AppAuthenticatedChatInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip': typeof VipRoute
  '/vip-club': typeof VipClubRoute
  '/app': typeof AppIndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app/auth': typeof AppAuthRoute
  '/app/auth-callback': typeof AppAuthCallbackRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/verify-otp': typeof AppVerifyOtpRoute
  '/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/chat/page': typeof AuthenticatedChatPageRoute
  '/app/admin': typeof AppAuthenticatedAdminRoute
  '/app/friends': typeof AppAuthenticatedFriendsRoute
  '/app/leaderboard': typeof AppAuthenticatedLeaderboardRoute
  '/app/onboarding': typeof AppAuthenticatedOnboardingRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/refer-earn': typeof AppAuthenticatedReferEarnRoute
  '/app/security': typeof AppAuthenticatedSecurityRoute
  '/app/vip-rewards': typeof AppAuthenticatedVipRewardsRoute
  '/app/wallet': typeof AppAuthenticatedWalletRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/app/chat/$friendId': typeof AppAuthenticatedChatFriendIdRoute
  '/app/chat/page': typeof AppAuthenticatedChatPageRoute
  '/app/u/$username': typeof AppAuthenticatedUUsernameRoute
  '/app/chat': typeof AppAuthenticatedChatIndexRoute
  '/app/chat/invite/$token': typeof AppAuthenticatedChatInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/vip': typeof VipRoute
  '/vip-club': typeof VipClubRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/app/auth': typeof AppAuthRoute
  '/app/auth-callback': typeof AppAuthCallbackRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/verify-otp': typeof AppVerifyOtpRoute
  '/app/': typeof AppIndexRoute
  '/_authenticated/chat/$friendId': typeof AuthenticatedChatFriendIdRoute
  '/_authenticated/chat/page': typeof AuthenticatedChatPageRoute
  '/app/_authenticated/admin': typeof AppAuthenticatedAdminRoute
  '/app/_authenticated/chat': typeof AppAuthenticatedChatRouteWithChildren
  '/app/_authenticated/friends': typeof AppAuthenticatedFriendsRoute
  '/app/_authenticated/leaderboard': typeof AppAuthenticatedLeaderboardRoute
  '/app/_authenticated/onboarding': typeof AppAuthenticatedOnboardingRoute
  '/app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/app/_authenticated/refer-earn': typeof AppAuthenticatedReferEarnRoute
  '/app/_authenticated/security': typeof AppAuthenticatedSecurityRoute
  '/app/_authenticated/vip-rewards': typeof AppAuthenticatedVipRewardsRoute
  '/app/_authenticated/wallet': typeof AppAuthenticatedWalletRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/app/_authenticated/chat/$friendId': typeof AppAuthenticatedChatFriendIdRoute
  '/app/_authenticated/chat/page': typeof AppAuthenticatedChatPageRoute
  '/app/_authenticated/u/$username': typeof AppAuthenticatedUUsernameRoute
  '/app/_authenticated/chat/': typeof AppAuthenticatedChatIndexRoute
  '/app/_authenticated/chat/invite/$token': typeof AppAuthenticatedChatInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/referrals'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip'
    | '/vip-club'
    | '/admin'
    | '/chat'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/app/auth'
    | '/app/auth-callback'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/verify-otp'
    | '/app/'
    | '/chat/$friendId'
    | '/chat/page'
    | '/app/admin'
    | '/app/chat'
    | '/app/friends'
    | '/app/leaderboard'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/refer-earn'
    | '/app/security'
    | '/app/vip-rewards'
    | '/app/wallet'
    | '/chat/'
    | '/app/chat/$friendId'
    | '/app/chat/page'
    | '/app/u/$username'
    | '/app/chat/'
    | '/app/chat/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/referrals'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip'
    | '/vip-club'
    | '/app'
    | '/admin'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/app/auth'
    | '/app/auth-callback'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/verify-otp'
    | '/chat/$friendId'
    | '/chat/page'
    | '/app/admin'
    | '/app/friends'
    | '/app/leaderboard'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/refer-earn'
    | '/app/security'
    | '/app/vip-rewards'
    | '/app/wallet'
    | '/chat'
    | '/app/chat/$friendId'
    | '/app/chat/page'
    | '/app/u/$username'
    | '/app/chat'
    | '/app/chat/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/auth-callback'
    | '/blog'
    | '/download'
    | '/faq'
    | '/forgot-password'
    | '/leaderboard'
    | '/privacy'
    | '/promotions'
    | '/referral'
    | '/referrals'
    | '/reset-password'
    | '/rewards'
    | '/support'
    | '/terms'
    | '/verify-otp'
    | '/vip'
    | '/vip-club'
    | '/app/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/friends'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/app/auth'
    | '/app/auth-callback'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/verify-otp'
    | '/app/'
    | '/_authenticated/chat/$friendId'
    | '/_authenticated/chat/page'
    | '/app/_authenticated/admin'
    | '/app/_authenticated/chat'
    | '/app/_authenticated/friends'
    | '/app/_authenticated/leaderboard'
    | '/app/_authenticated/onboarding'
    | '/app/_authenticated/profile'
    | '/app/_authenticated/refer-earn'
    | '/app/_authenticated/security'
    | '/app/_authenticated/vip-rewards'
    | '/app/_authenticated/wallet'
    | '/_authenticated/chat/'
    | '/app/_authenticated/chat/$friendId'
    | '/app/_authenticated/chat/page'
    | '/app/_authenticated/u/$username'
    | '/app/_authenticated/chat/'
    | '/app/_authenticated/chat/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogRoute: typeof BlogRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  PromotionsRoute: typeof PromotionsRoute
  ReferralRoute: typeof ReferralRoute
  ReferralsRoute: typeof ReferralsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  VipRoute: typeof VipRoute
  VipClubRoute: typeof VipClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-club': {
      id: '/vip-club'
      path: '/vip-club'
      fullPath: '/vip-club'
      preLoaderRoute: typeof VipClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify-otp': {
      id: '/app/verify-otp'
      path: '/verify-otp'
      fullPath: '/app/verify-otp'
      preLoaderRoute: typeof AppVerifyOtpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reset-password': {
      id: '/app/reset-password'
      path: '/reset-password'
      fullPath: '/app/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auth-callback': {
      id: '/app/auth-callback'
      path: '/auth-callback'
      fullPath: '/app/auth-callback'
      preLoaderRoute: typeof AppAuthCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/app/_authenticated/wallet': {
      id: '/app/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppAuthenticatedWalletRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/vip-rewards': {
      id: '/app/_authenticated/vip-rewards'
      path: '/vip-rewards'
      fullPath: '/app/vip-rewards'
      preLoaderRoute: typeof AppAuthenticatedVipRewardsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/security': {
      id: '/app/_authenticated/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppAuthenticatedSecurityRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/refer-earn': {
      id: '/app/_authenticated/refer-earn'
      path: '/refer-earn'
      fullPath: '/app/refer-earn'
      preLoaderRoute: typeof AppAuthenticatedReferEarnRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/profile': {
      id: '/app/_authenticated/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/onboarding': {
      id: '/app/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppAuthenticatedOnboardingRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/leaderboard': {
      id: '/app/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppAuthenticatedLeaderboardRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/friends': {
      id: '/app/_authenticated/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppAuthenticatedFriendsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/chat': {
      id: '/app/_authenticated/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppAuthenticatedChatRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/admin': {
      id: '/app/_authenticated/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAuthenticatedAdminRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_authenticated/chat/page': {
      id: '/_authenticated/chat/page'
      path: '/page'
      fullPath: '/chat/page'
      preLoaderRoute: typeof AuthenticatedChatPageRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$friendId': {
      id: '/_authenticated/chat/$friendId'
      path: '/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof AuthenticatedChatFriendIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/app/_authenticated/chat/': {
      id: '/app/_authenticated/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppAuthenticatedChatIndexRouteImport
      parentRoute: typeof AppAuthenticatedChatRoute
    }
    '/app/_authenticated/u/$username': {
      id: '/app/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/app/u/$username'
      preLoaderRoute: typeof AppAuthenticatedUUsernameRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/chat/page': {
      id: '/app/_authenticated/chat/page'
      path: '/page'
      fullPath: '/app/chat/page'
      preLoaderRoute: typeof AppAuthenticatedChatPageRouteImport
      parentRoute: typeof AppAuthenticatedChatRoute
    }
    '/app/_authenticated/chat/$friendId': {
      id: '/app/_authenticated/chat/$friendId'
      path: '/$friendId'
      fullPath: '/app/chat/$friendId'
      preLoaderRoute: typeof AppAuthenticatedChatFriendIdRouteImport
      parentRoute: typeof AppAuthenticatedChatRoute
    }
    '/app/_authenticated/chat/invite/$token': {
      id: '/app/_authenticated/chat/invite/$token'
      path: '/invite/$token'
      fullPath: '/app/chat/invite/$token'
      preLoaderRoute: typeof AppAuthenticatedChatInviteTokenRouteImport
      parentRoute: typeof AppAuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatFriendIdRoute: typeof AuthenticatedChatFriendIdRoute
  AuthenticatedChatPageRoute: typeof AuthenticatedChatPageRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatFriendIdRoute: AuthenticatedChatFriendIdRoute,
  AuthenticatedChatPageRoute: AuthenticatedChatPageRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppAuthenticatedChatRouteChildren {
  AppAuthenticatedChatFriendIdRoute: typeof AppAuthenticatedChatFriendIdRoute
  AppAuthenticatedChatPageRoute: typeof AppAuthenticatedChatPageRoute
  AppAuthenticatedChatIndexRoute: typeof AppAuthenticatedChatIndexRoute
  AppAuthenticatedChatInviteTokenRoute: typeof AppAuthenticatedChatInviteTokenRoute
}

const AppAuthenticatedChatRouteChildren: AppAuthenticatedChatRouteChildren = {
  AppAuthenticatedChatFriendIdRoute: AppAuthenticatedChatFriendIdRoute,
  AppAuthenticatedChatPageRoute: AppAuthenticatedChatPageRoute,
  AppAuthenticatedChatIndexRoute: AppAuthenticatedChatIndexRoute,
  AppAuthenticatedChatInviteTokenRoute: AppAuthenticatedChatInviteTokenRoute,
}

const AppAuthenticatedChatRouteWithChildren =
  AppAuthenticatedChatRoute._addFileChildren(AppAuthenticatedChatRouteChildren)

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedAdminRoute: typeof AppAuthenticatedAdminRoute
  AppAuthenticatedChatRoute: typeof AppAuthenticatedChatRouteWithChildren
  AppAuthenticatedFriendsRoute: typeof AppAuthenticatedFriendsRoute
  AppAuthenticatedLeaderboardRoute: typeof AppAuthenticatedLeaderboardRoute
  AppAuthenticatedOnboardingRoute: typeof AppAuthenticatedOnboardingRoute
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
  AppAuthenticatedReferEarnRoute: typeof AppAuthenticatedReferEarnRoute
  AppAuthenticatedSecurityRoute: typeof AppAuthenticatedSecurityRoute
  AppAuthenticatedVipRewardsRoute: typeof AppAuthenticatedVipRewardsRoute
  AppAuthenticatedWalletRoute: typeof AppAuthenticatedWalletRoute
  AppAuthenticatedUUsernameRoute: typeof AppAuthenticatedUUsernameRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedAdminRoute: AppAuthenticatedAdminRoute,
  AppAuthenticatedChatRoute: AppAuthenticatedChatRouteWithChildren,
  AppAuthenticatedFriendsRoute: AppAuthenticatedFriendsRoute,
  AppAuthenticatedLeaderboardRoute: AppAuthenticatedLeaderboardRoute,
  AppAuthenticatedOnboardingRoute: AppAuthenticatedOnboardingRoute,
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
  AppAuthenticatedReferEarnRoute: AppAuthenticatedReferEarnRoute,
  AppAuthenticatedSecurityRoute: AppAuthenticatedSecurityRoute,
  AppAuthenticatedVipRewardsRoute: AppAuthenticatedVipRewardsRoute,
  AppAuthenticatedWalletRoute: AppAuthenticatedWalletRoute,
  AppAuthenticatedUUsernameRoute: AppAuthenticatedUUsernameRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppAuthRoute: typeof AppAuthRoute
  AppAuthCallbackRoute: typeof AppAuthCallbackRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppVerifyOtpRoute: typeof AppVerifyOtpRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppAuthRoute: AppAuthRoute,
  AppAuthCallbackRoute: AppAuthCallbackRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppVerifyOtpRoute: AppVerifyOtpRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogRoute: BlogRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  PromotionsRoute: PromotionsRoute,
  ReferralRoute: ReferralRoute,
  ReferralsRoute: ReferralsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  VipRoute: VipRoute,
  VipClubRoute: VipClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
