// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
    realtime: {
      url: "wss://ws.playjackpotjungle.com/realtime/v1/websocket"
    }
  });

  // Intercept storage client public URLs to serve from the CDN subdomain
  const originalFrom = client.storage.from.bind(client.storage);
  client.storage.from = (id: string) => {
    const bucketClient = originalFrom(id);
    const originalGetPublicUrl = bucketClient.getPublicUrl.bind(bucketClient);
    bucketClient.getPublicUrl = (path: string, options?: any) => {
      const res = originalGetPublicUrl(path, options);
      if (res.data?.publicUrl) {
        const cdnUrl = "https://cdn.playjackpotjungle.com";
        const storagePrefix = `${SUPABASE_URL}/storage/v1/object/public`;
        if (res.data.publicUrl.startsWith(storagePrefix)) {
          res.data.publicUrl = res.data.publicUrl.replace(storagePrefix, `${cdnUrl}/${id}`);
        }
      }
      return res;
    };
    return bucketClient;
  };

  return client;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
