// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? {
        getItem: (key: string) => {
          const cookieMatch = document.cookie.match('(^|;)\\s*' + key + '\\s*=\\s*([^;]+)');
          if (cookieMatch) {
            return decodeURIComponent(cookieMatch.pop() || '');
          }
          return localStorage.getItem(key);
        },
        setItem: (key: string, value: string) => {
          localStorage.setItem(key, value);
          const isProdDomain = window.location.hostname.endsWith('playjackpotjungle.com');
          const domain = isProdDomain ? '; domain=.playjackpotjungle.com; path=/' : '; path=/';
          document.cookie = `${key}=${encodeURIComponent(value)}${domain}; max-age=31536000; SameSite=Lax; Secure`;
        },
        removeItem: (key: string) => {
          localStorage.removeItem(key);
          const isProdDomain = window.location.hostname.endsWith('playjackpotjungle.com');
          const domain = isProdDomain ? '; domain=.playjackpotjungle.com; path=/' : '; path=/';
          document.cookie = `${key}=; expires=Thu, 01 Jan 1970 00:00:00 UTC${domain}`;
        }
      } : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      url: "wss://ws.playjackpotjungle.com/realtime/v1/websocket"
    }
  });

  // Intercept storage client public URLs to serve from the CDN subdomain
  const originalFrom = client.storage.from.bind(client.storage);
  client.storage.from = (id: string) => {
    const bucketClient = originalFrom(id);
    const originalGetPublicUrl = bucketClient.getPublicUrl.bind(bucketClient);
    bucketClient.getPublicUrl = (path: string, options?: any) => {
      const res = originalGetPublicUrl(path, options);
      if (res.data?.publicUrl) {
        const cdnUrl = "https://cdn.playjackpotjungle.com";
        const storagePrefix = `${SUPABASE_URL}/storage/v1/object/public`;
        if (res.data.publicUrl.startsWith(storagePrefix)) {
          res.data.publicUrl = res.data.publicUrl.replace(storagePrefix, `${cdnUrl}/${id}`);
        }
      }
      return res;
    };
    return bucketClient;
  };

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

